apiVersion: v1
kind: Service
metadata:
  name: wp-mysql
  labels:
    name: wordpress
  namespace: wordpress
spec:
  type: ClusterIP
  selector:
    app: wordpress
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80